//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIEN_CNPMNC_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.PhieuMuonTras = new HashSet<PhieuMuonTra>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaTheLoai { get; set; }
        public string MaNXB { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NamXuatBan { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> TrungBay { get; set; }
        public string MaPN { get; set; }
        public Nullable<int> LuotMuonTra { get; set; }
    
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuonTra> PhieuMuonTras { get; set; }
    }
}
