//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIEN_CNPMNC_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuPhat
    {
        public string MaPhieuPhat { get; set; }
        public string MaPhieuMuon { get; set; }
        public string MaThuThu { get; set; }
        public Nullable<int> SoNgayTre { get; set; }
        public Nullable<System.DateTime> NgayPhat { get; set; }
        public Nullable<int> SoTienPhat { get; set; }
    
        public virtual PhieuMuonTra PhieuMuonTra { get; set; }
        public virtual ThuThu ThuThu { get; set; }
    }
}
