//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIEN_CNPMNC_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheDocGia
    {
        public string MaThe { get; set; }
        public string MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
